language: node_js
services:
- mongodb
- redis-server
node_js:
- '0.10'
before_script: npm install --dev
script: npm test
env:
  global:
  - PROVIDER_URL="http://localhost:8000"
  - ANYFETCH_API_ID="CLUESTR-ID"
  - ANYFETCH_API_SECRET="CLUESTR-SECRET"
  - secure: OFxTlQ9z2GWkrQ1ZXB7GfoLv3npN9qP1toX68nvZeKoV2yIYctJn+kS+kHogclpP5KQs7mOImEkVHrFwUHamXe/GeJJwwTuMBKJfM6+jntXsoTPnb5Apbuev181rWHozH6iGzrQZ064SW02r+UE+ZK2E/LTfSLKyCGOP1IWqvHM=
  - secure: YSVwpbrPNarhvh/sGONmmVkjuZnrsprYWRjHFPhdhHqeMmuGPsta4quHKs8VZ3rbSid3EivJLIkjNyBovCS4TL3Rsd+R6NcJqiNT7XL7VFZvRgydHLRjfR/S6jZCY4q9CjVHB3MQ/1cYjnNUeXaBPBf2czQ6aEQt5NyFLSX8yIM=
  - secure: ZFirnT/eBpXLxs69FdqHN9+dehg7Cn2FI0EkTxBac640Fw74FsLydCqT2nhPhHymRDTVCiiMioZpNQfstu2zvtmThd7RPkyQu8IA8qY08isAlIcf9HjaOPV2NDQWKtuB7IDQ3HAjrpP51Ar8uIrXBZsnm9BXNguqfkONBSoiKsQ=
  - secure: Et/OEHjuC1MzVTGgdBL9DC9szGFDmUI38VCK6vPflgiGhdSTbXno9YxEnHu00WhNBrjU/mPezQX/TUuDDSqv7qua76cdTLskJnZC4XyHDndGlh9NpsG+BVIdzZt/kCAuUmVNO3UHkig/GM/pR8ql1F6VPiiYcweZuzsScJpSlcI=
