language: node_js
services: mongodb
node_js:
- '0.10'
before_script: npm install --dev
script: npm test
env:
  global:
    - PROVIDER_URL="http://localhost:8000"
    - PROVIDER_ANYFETCH_ID="CLUESTR-ID"
    - PROVIDER_ANYFETCH_SECRET="CLUESTR-SECRET"
